// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _gen_pwm_HH_
#define _gen_pwm_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct gen_pwm : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > duty;
    sc_in< sc_lv<32> > freq;
    sc_out< sc_lv<8> > out_r;
    sc_out< sc_logic > out_r_ap_vld;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    gen_pwm(sc_module_name name);
    SC_HAS_PROCESS(gen_pwm);

    ~gen_pwm();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_18;
    sc_signal< sc_lv<31> > i_1_fu_74_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_47;
    sc_signal< sc_lv<31> > i_reg_53;
    sc_signal< sc_lv<1> > tmp_fu_69_p2;
    sc_signal< sc_lv<32> > i_cast_fu_65_p1;
    sc_signal< sc_lv<1> > tmp_1_fu_80_p2;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    sc_signal< bool > ap_sig_bdd_36;
    sc_signal< bool > ap_sig_bdd_91;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_st1_fsm_0;
    static const sc_lv<2> ap_ST_st2_fsm_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<31> ap_const_lv31_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_18();
    void thread_ap_sig_bdd_36();
    void thread_ap_sig_bdd_47();
    void thread_ap_sig_bdd_91();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_i_1_fu_74_p2();
    void thread_i_cast_fu_65_p1();
    void thread_out_r();
    void thread_out_r_ap_vld();
    void thread_tmp_1_fu_80_p2();
    void thread_tmp_fu_69_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
