# Set attributes defining registered ports.

set_attribute -quiet -type boolean [find port {HCLK_hclk}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {HRESETn_hresetn}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {PCLK_pclk}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {PRESETn_presetn}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[11]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[10]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[9]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[8]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[1]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_haddr[0]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hburst[2]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hburst[1]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hburst[0]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hlock}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hprot[3]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hprot[2]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hprot[1]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hprot[0]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hsize[2]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hsize[1]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hsize[0]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_htrans[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_htrans[0]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[31]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[30]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[29]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[28]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[27]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[26]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[25]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[24]}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hwrite}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hrdata[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hready_resp}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hresp[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hresp[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hrdata[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hready_resp}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hresp[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hresp[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hrdata[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hready_resp}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hresp[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hresp[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {i_apb_pclk_en}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {i_i2c_ic_clk}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_clk_in_a}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {i_i2c_ic_data_in_a}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {i_i2c_ic_rst_n}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {i_ssi_rxd}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {i_ssi_ss_in_n}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {i_ssi_ssi_clk}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {i_ssi_ssi_rst_n}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[31]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[30]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[29]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[28]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[27]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[26]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[25]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[24]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[23]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[22]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[21]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[20]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[19]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[18]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[17]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[16]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[15]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[14]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[13]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[12]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[11]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[10]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[9]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[8]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[7]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[6]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[5]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[4]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hready}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hresp[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_MASTER_CORTEXM0_hresp[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[31]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[30]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[29]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[28]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[27]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[26]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[25]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[24]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[23]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[22]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[21]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[20]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[19]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[18]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[17]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[16]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[15]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[14]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[13]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[12]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[11]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[10]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[9]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[8]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[7]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[6]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[5]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[4]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_haddr[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hburst[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hburst[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hburst[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hmastlock}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hprot[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hprot[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hprot[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hprot[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hready}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hsel}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hsize[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hsize[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hsize[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_htrans[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_htrans[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[31]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[30]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[29]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[28]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[27]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[26]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[25]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[24]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[23]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[22]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[21]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[20]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[19]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[18]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[17]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[16]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[15]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[14]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[13]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[12]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[11]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[10]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[9]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[8]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[7]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[6]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[5]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[4]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwdata[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PID_hwrite}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[31]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[30]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[29]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[28]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[27]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[26]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[25]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[24]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[23]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[22]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[21]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[20]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[19]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[18]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[17]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[16]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[15]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[14]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[13]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[12]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[11]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[10]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[9]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[8]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[7]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[6]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[5]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[4]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_haddr[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hburst[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hburst[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hburst[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hmastlock}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hprot[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hprot[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hprot[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hprot[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hready}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hsel}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hsize[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hsize[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hsize[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_htrans[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_htrans[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[31]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[30]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[29]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[28]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[27]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[26]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[25]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[24]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[23]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[22]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[21]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[20]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[19]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[18]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[17]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[16]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[15]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[14]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[13]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[12]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[11]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[10]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[9]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[8]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[7]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[6]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[5]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[4]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwdata[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_PWM_hwrite}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[31]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[30]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[29]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[28]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[27]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[26]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[25]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[24]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[23]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[22]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[21]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[20]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[19]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[18]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[17]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[16]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[15]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[14]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[13]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[12]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[11]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[10]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[9]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[8]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[7]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[6]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[5]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[4]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_haddr[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hburst[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hburst[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hburst[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hmastlock}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hprot[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hprot[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hprot[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hprot[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hready}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hsel}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hsize[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hsize[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hsize[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_htrans[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_htrans[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[31]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[30]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[29]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[28]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[27]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[26]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[25]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[24]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[23]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[22]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[21]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[20]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[19]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[18]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[17]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[16]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[15]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[14]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[13]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[12]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[11]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[10]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[9]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[8]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[7]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[6]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[5]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[4]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwdata[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_RAM_hwrite}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hmaster_data[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hmaster_data[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hmaster_data[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hmaster_data[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_i2c_debug_addr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_addr_10bit}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_data}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_hs}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_master_act}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_mst_cstate[4]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_mst_cstate[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_mst_cstate[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_mst_cstate[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_mst_cstate[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_p_gen}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_rd}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_s_gen}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_slave_act}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_slv_cstate[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_slv_cstate[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_slv_cstate[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_slv_cstate[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_wr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_activity_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_clk_oe}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_current_src_en}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_data_oe}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_en}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_gen_call_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_rd_req_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_rx_done_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_rx_full_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_rx_over_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_rx_under_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_start_det_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_stop_det_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_tx_abrt_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_tx_empty_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_tx_over_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ssi_sclk_out}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ssi_ss_0_n}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ssi_ssi_mst_intr_n}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ssi_ssi_oe_n}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ssi_ssi_rxf_intr_n}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ssi_ssi_rxo_intr_n}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ssi_ssi_rxu_intr_n}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ssi_ssi_sleep}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ssi_ssi_txe_intr_n}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ssi_ssi_txo_intr_n}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ssi_txd}] rtIsRegisteredOutput true
