# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1

create_project -in_memory -part xc7k325tffg676-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.cache/wt [current_project]
set_property parent.project_path /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0.xci
set_property is_locked true [get_files /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file axi_intc_0.hwdef }
synth_design -top axi_intc_0 -part xc7k325tffg676-2 -mode out_of_context
rename_ref -prefix_all axi_intc_0_
write_checkpoint -noxdef axi_intc_0.dcp
catch { report_utilization -file axi_intc_0_utilization_synth.rpt -pb axi_intc_0_utilization_synth.pb }
if { [catch {
  file copy -force /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.runs/axi_intc_0_synth_1/axi_intc_0.dcp /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
