# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0.xci
# IP: The module: 'axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0.xci
# IP: The module: 'axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/warehouse/l.kirchner/566_project/vivado_src/vivado_src.srcs/sources_1/ip/axi_intc_0/axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
