# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z010clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/warehouse/lbremer/ese566/workload_PID/hls/fixp/hls_fixedp_pid_prj/solution_fixedp/impl/vhdl/project.cache/wt [current_project]
set_property parent.project_path /home/warehouse/lbremer/ese566/workload_PID/hls/fixp/hls_fixedp_pid_prj/solution_fixedp/impl/vhdl/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib /home/warehouse/lbremer/ese566/workload_PID/hls/fixp/hls_fixedp_pid_prj/solution_fixedp/impl/vhdl/PID_Controller.vhd
read_xdc /home/warehouse/lbremer/ese566/workload_PID/hls/fixp/hls_fixedp_pid_prj/solution_fixedp/impl/vhdl/PID_Controller.xdc
set_property used_in_implementation false [get_files /home/warehouse/lbremer/ese566/workload_PID/hls/fixp/hls_fixedp_pid_prj/solution_fixedp/impl/vhdl/PID_Controller.xdc]

catch { write_hwdef -file PID_Controller.hwdef }
synth_design -top PID_Controller -part xc7z010clg400-1 -no_iobuf -mode out_of_context
write_checkpoint -noxdef PID_Controller.dcp
catch { report_utilization -file PID_Controller_utilization_synth.rpt -pb PID_Controller_utilization_synth.pb }
