#
# This file is auto generated by coreConsultant for use in Leda CDC rule checkers
#
set_clock_group -name SSI_CLK -synchronous -group i_ssi_DW_apb_ssi.ssi_clk
set_clock_group -name PCLK    -synchronous -group i_ssi_DW_apb_ssi.pclk

set_cdc_ignored_path -from i_ssi_DW_apb_ssi.U_regfile.ctrlr0_ir*
set_cdc_ignored_path -from i_ssi_DW_apb_ssi.U_regfile.mwcr_ir*
set_cdc_ignored_path -from i_ssi_DW_apb_ssi.U_regfile.imr_ir*
set_cdc_ignored_path -from i_ssi_DW_apb_ssi.U_dff_tx.mem*
set_cdc_ignored_path -from i_ssi_DW_apb_ssi.U_shift.U_rx_shifter.rx_buffer*
set_cdc_ignored_path -from i_ssi_DW_apb_ssi.U_regfile.ctrlr1_ir*
set_cdc_ignored_path -from i_ssi_DW_apb_ssi.U_regfile.baudr_ir*
set_cdc_ignored_path -from i_ssi_DW_apb_ssi.U_regfile.baud2_ir*
set_cdc_ignored_path -from i_ssi_DW_apb_ssi.U_regfile.ser_ir*

