// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


extern void PID_Controller ( bool InitN,  ap_fixed<25, 10, (ap_q_mode) 5, (ap_o_mode)3, 0> coeff[6],  ap_fixed<25, 10, (ap_q_mode) 5, (ap_o_mode)3, 0> din[2],  ap_fixed<25, 10, (ap_q_mode) 5, (ap_o_mode)3, 0> dout[2]);

