# Set attributes defining registered ports.

set_attribute -quiet -type boolean [find port {hclk}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {hresetn}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {haddr_m1[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {haddr_m1[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hburst_m1[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hburst_m1[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hburst_m1[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hlock_m1}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hprot_m1[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hprot_m1[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hprot_m1[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hprot_m1[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hsize_m1[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hsize_m1[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hsize_m1[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {htrans_m1[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {htrans_m1[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwdata_m1[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hwrite_m1}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hready_resp_s1}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hresp_s1[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hresp_s1[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s1[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hready_resp_s2}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hresp_s2[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hresp_s2[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s2[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hready_resp_s3}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hresp_s3[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hresp_s3[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s3[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hready_resp_s4}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hresp_s4[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hresp_s4[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hrdata_s4[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {hsel_s1}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hsel_s2}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hsel_s3}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hsel_s4}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[31]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[30]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[29]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[28]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[27]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[26]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[25]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[24]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[23]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[22]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[21]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[20]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[19]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[18]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[17]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[16]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[15]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[14]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[13]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[12]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[11]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[10]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[9]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[8]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[7]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[6]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[5]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[4]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {haddr[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hburst[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hburst[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hburst[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hprot[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hprot[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hprot[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hprot[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hsize[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hsize[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hsize[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {htrans[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {htrans[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[31]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[30]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[29]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[28]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[27]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[26]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[25]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[24]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[23]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[22]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[21]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[20]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[19]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[18]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[17]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[16]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[15]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[14]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[13]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[12]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[11]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[10]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[9]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[8]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[7]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[6]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[5]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[4]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwdata[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hwrite}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hready}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hresp[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hresp[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[31]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[30]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[29]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[28]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[27]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[26]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[25]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[24]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[23]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[22]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[21]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[20]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[19]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[18]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[17]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[16]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[15]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[14]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[13]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[12]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[11]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[10]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[9]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[8]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[7]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[6]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[5]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[4]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hrdata[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hmaster[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hmaster[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hmaster[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hmaster[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hmaster_data[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hmaster_data[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hmaster_data[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hmaster_data[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {hmastlock}] rtIsRegisteredOutput true
