//------------------------------------------------------------------------------
// WUSTL ESE 566
// Authors: Leo Bremer
// Date: 11/12/1015
//
// Description: Top-level RTL to connect various IP blocks. In
// this module the CORTEXM0DS processor and the IP generated by the
// coreAssembler tool are connected through an AHB-Lite interface.
//
// Status: Waiting for APB peripherals, memory, and accelerator wrappers
//
// Testing: TODO
// 
//------------------------------------------------------------------------------

module system_top (
  // CLOCK AND RESETS ------------------
  input  wire        HCLK_top   (HCLK_top_top),              // Clock
  input  wire        HRESETn_top         // Asynchronous reset
);

//------------------------------------------------------------------------------
// Internal Signals
//------------------------------------------------------------------------------
    // AHB-LITE CORTEX M0 INTERFACE  --------------
    wire [31:0] HADDR_top;             // AHB transaction address
    wire [ 2:0] HBURST_top;            // AHB burst: tied to single
    wire        HMASTLOCK_top;         // AHB locked transfer (always zero)
    wire [ 3:0] HPROT_top;             // AHB protection: priv; data or inst
    wire [ 2:0] HSIZE_top;             // AHB size: byte, half-word or word
    wire [ 1:0] HTRANS_top;            // AHB transfer: non-sequential only
    wire [31:0] HWDATA_top;            // AHB write-data
    wire        HWRITE_top;            // AHB write control
    wire [31:0] HRDATA_top;            // AHB read-data
    wire        HREADY_top;            // AHB stall signal
    wire        HRESP_top;             // AHB error response
    // PWM ACCELERATOR INTERFACE
    wire PWM_hrdata_top;
    wire PWM_hready_resp_top;
    wire PWM_hresp_top;
    wire PWM_haddr_top;
    wire PWM_hburst_top;
    wire PWM_hmastlock_top;
    wire PWM_hprot_top;
    wire PWM_hready_top;
    wire PWM_hsel_top;
    wire PWM_hsize_top;
    wire PWM_htrans_top;
    wire PWM_hwdata_top;
    wire PWM_hwrite_top;
    wire out_pwm_top;

//------------------------------------------------------------------------------
// Instantiate coreAssembler-generated AMBA IP
//------------------------------------------------------------------------------
interconnect_ip interconnect_ip_inst (       // Ports for Interface HCLK
                        .HCLK_hclk(HCLK_top),
                        // Ports for Interface HRESETn
                        .HRESETn_hresetn(HRESETn_top),
                        // Ports for Interface PCLK
                        .PCLK_pclk(HCLK_top),
                        // Ports for Interface PRESETn
                        .PRESETn_presetn(HRESETn_top),
                        // Ports for Interface ex_i_ahb_AHB_MASTER_CORTEXM0
                        .ex_i_ahb_AHB_MASTER_CORTEXM0_haddr(HADDR_top),
                        .ex_i_ahb_AHB_MASTER_CORTEXM0_hburst(HBURST_top),
                        .ex_i_ahb_AHB_MASTER_CORTEXM0_hlock(HMASTLOCK_top),
                        .ex_i_ahb_AHB_MASTER_CORTEXM0_hprot(HPROT_top),
                        .ex_i_ahb_AHB_MASTER_CORTEXM0_hsize(HSIZE_top),
                        .ex_i_ahb_AHB_MASTER_CORTEXM0_htrans(HTRANS_top),
                        .ex_i_ahb_AHB_MASTER_CORTEXM0_hwdata(HWDATA_top),
                        .ex_i_ahb_AHB_MASTER_CORTEXM0_hwrite(HWRITE_top),
                        .ex_i_ahb_AHB_MASTER_CORTEXM0_hrdata(HRDATA_top),
                        .ex_i_ahb_AHB_MASTER_CORTEXM0_hready(HREADY_top),
                        .ex_i_ahb_AHB_MASTER_CORTEXM0_hresp(HRESP_top),
                        // Ports for Interface ex_i_ahb_AHB_Slave_PID
                        ex_i_ahb_AHB_Slave_PID_hrdata,
                        ex_i_ahb_AHB_Slave_PID_hready_resp,
                        ex_i_ahb_AHB_Slave_PID_hresp,
                        ex_i_ahb_AHB_Slave_PID_haddr,
                        ex_i_ahb_AHB_Slave_PID_hburst,
                        ex_i_ahb_AHB_Slave_PID_hmastlock,
                        ex_i_ahb_AHB_Slave_PID_hprot,
                        ex_i_ahb_AHB_Slave_PID_hready,
                        ex_i_ahb_AHB_Slave_PID_hsel,
                        ex_i_ahb_AHB_Slave_PID_hsize,
                        ex_i_ahb_AHB_Slave_PID_htrans,
                        ex_i_ahb_AHB_Slave_PID_hwdata,
                        ex_i_ahb_AHB_Slave_PID_hwrite,
                        // Ports for Interface ex_i_ahb_AHB_Slave_PWM
                        ex_i_ahb_AHB_Slave_PWM_hrdata(PWM_hrdata_top),
                        ex_i_ahb_AHB_Slave_PWM_hready_resp(PWM_hready_resp_top)
                        ex_i_ahb_AHB_Slave_PWM_hresp(PWM_hresp_top),
                        ex_i_ahb_AHB_Slave_PWM_haddr(PWM_haddr_top),
                        ex_i_ahb_AHB_Slave_PWM_hburst(PWM_hburst_top),
                        ex_i_ahb_AHB_Slave_PWM_hmastlock(PWM_hmastlock_top),
                        ex_i_ahb_AHB_Slave_PWM_hprot(PWM_hprot_top),
                        ex_i_ahb_AHB_Slave_PWM_hready(PWM_hready_top),
                        ex_i_ahb_AHB_Slave_PWM_hsel(PWM_hsel_top),
                        ex_i_ahb_AHB_Slave_PWM_hsize(PWM_hsize_top),
                        ex_i_ahb_AHB_Slave_PWM_htrans(PWM_htrans_top),
                        ex_i_ahb_AHB_Slave_PWM_hwdata(PWM_hwdata_top),
                        ex_i_ahb_AHB_Slave_PWM_hwrite(PWM_hwrite_top),
                        out_pwm(out_pwm_top),
                        // Ports for Interface ex_i_ahb_AHB_Slave_RAM
                        ex_i_ahb_AHB_Slave_RAM_hrdata,
                        ex_i_ahb_AHB_Slave_RAM_hready_resp,
                        ex_i_ahb_AHB_Slave_RAM_hresp,
                        ex_i_ahb_AHB_Slave_RAM_haddr,
                        ex_i_ahb_AHB_Slave_RAM_hburst,
                        ex_i_ahb_AHB_Slave_RAM_hmastlock,
                        ex_i_ahb_AHB_Slave_RAM_hprot,
                        ex_i_ahb_AHB_Slave_RAM_hready,
                        ex_i_ahb_AHB_Slave_RAM_hsel,
                        ex_i_ahb_AHB_Slave_RAM_hsize,
                        ex_i_ahb_AHB_Slave_RAM_htrans,
                        ex_i_ahb_AHB_Slave_RAM_hwdata,
                        ex_i_ahb_AHB_Slave_RAM_hwrite,
                        // Ports for Manually exported pins
                        i_apb_pclk_en,
                        i_i2c_ic_clk,
                        i_i2c_ic_clk_in_a,
                        i_i2c_ic_data_in_a,
                        i_i2c_ic_rst_n,
                        i_ssi_rxd,
                        i_ssi_ss_in_n,
                        i_ssi_ssi_clk,
                        i_ssi_ssi_rst_n,
                        i_ahb_hmaster_data,
                        i_i2c_debug_addr,
                        i_i2c_debug_addr_10bit,
                        i_i2c_debug_data,
                        i_i2c_debug_hs,
                        i_i2c_debug_master_act,
                        i_i2c_debug_mst_cstate,
                        i_i2c_debug_p_gen,
                        i_i2c_debug_rd,
                        i_i2c_debug_s_gen,
                        i_i2c_debug_slave_act,
                        i_i2c_debug_slv_cstate,
                        i_i2c_debug_wr,
                        i_i2c_ic_activity_intr,
                        i_i2c_ic_clk_oe,
                        i_i2c_ic_current_src_en,
                        i_i2c_ic_data_oe,
                        i_i2c_ic_en,
                        i_i2c_ic_gen_call_intr,
                        i_i2c_ic_rd_req_intr,
                        i_i2c_ic_rx_done_intr,
                        i_i2c_ic_rx_full_intr,
                        i_i2c_ic_rx_over_intr,
                        i_i2c_ic_rx_under_intr,
                        i_i2c_ic_start_det_intr,
                        i_i2c_ic_stop_det_intr,
                        i_i2c_ic_tx_abrt_intr,
                        i_i2c_ic_tx_empty_intr,
                        i_i2c_ic_tx_over_intr,
                        i_ssi_sclk_out,
                        i_ssi_ss_0_n,
                        i_ssi_ssi_mst_intr_n,
                        i_ssi_ssi_oe_n,
                        i_ssi_ssi_rxf_intr_n,
                        i_ssi_ssi_rxo_intr_n,
                        i_ssi_ssi_rxu_intr_n,
                        i_ssi_ssi_sleep,
                        i_ssi_ssi_txe_intr_n,
                        i_ssi_ssi_txo_intr_n,
                        i_ssi_txd
                        );

//------------------------------------------------------------------------------
// Instantiate Cortex-M0 processor 
//------------------------------------------------------------------------------
CORTEXM0DS CORTEXM0DS_INST(
  // CLOCK AND RESETS ------------------
  .HCLK     (HLCK_top),             // Clock input
  .HRESETn      (HRESETn_top),           // Asynchronous reset input
  // AHB-LITE MASTER PORT .--------------
  .HADDR    (HADDR_top),             // AHB transaction address outpu(out_top)t
  .HBURST   (HBURST_top),            // AHB burst: tied to single output
  .HMASTLOCK    (HMASTLOCK_top),         // AHB locked transfer (always zero) output
  .HPROT    (HPROT_top),             // AHB protection: priv; data or inst output
  .HSIZE    (HSIZE_top),             // AHB size: byte, half-word or word output
  .HTRANS   (HTRANS_top),            // AHB transfer: non-sequential only output
  .HWDATA   (HWDATA_top),            // AHB write-data output
  .HWRITE   (HWRITE_top),            // AHB write control output
  .HRDATA   (HRDATA_top),            // AHB read-data input
  .HREADY   (HREADY_top),            // AHB stall signal input
  .HRESP    (HRESP_top),             // AHB error response input
  // MISCELLANEOUS ---------------------
  .NMI  (NMI_top),                   // Non-maskable interrupt input 
  .IRQ  (IRQ_top),                   // Interrupt request inputs 
  .TXEV (TXEV_top),                  // Event output (SEV executed) output
  .RXEV (RXEV_top),                  // Event input 
  .LOCKUP   (LOCKUP_top),            // Core is locked-up output
  .SYSRESETREQ  (SYSRESETREQ_top),   // System reset request output
  // POWER MANAGEMENT ------------------
  .SLEEPING     (SLEEPING_top)       // Core and NVIC sleeping output
);

pwm2ahb_wrapper pwm2ahb_wrapper_inst (
    // Clock and reset
    .HCLK(HCLK_top),
    .HRESETn(HRESETn_top),
    // AHB Interface
    .ex_i_ahb_AHB_Slave_PWM_hrdata(PWM_hrdata_top),
    .ex_i_ahb_AHB_Slave_PWM_hready_resp(PWM_hready_resp_top),
    .ex_i_ahb_AHB_Slave_PWM_hresp(PWM_hresp_top),
    .ex_i_ahb_AHB_Slave_PWM_haddr(PWM_haddr_top),
    .ex_i_ahb_AHB_Slave_PWM_hburst(PWM_hburst_top),
    .ex_i_ahb_AHB_Slave_PWM_hmastlock(PWM_hmastlock_top),
    .ex_i_ahb_AHB_Slave_PWM_hprot(PWM_hprot_top),
    .ex_i_ahb_AHB_Slave_PWM_hready(PWM_hready_top),
    .ex_i_ahb_AHB_Slave_PWM_hsel(PWM_hsel_top),
    .ex_i_ahb_AHB_Slave_PWM_hsize(PWM_hsize_top),
    .ex_i_ahb_AHB_Slave_PWM_htrans(PWM_htrans_top),
    .ex_i_ahb_AHB_Slave_PWM_hwdata(PWM_hwdata_top),
    .ex_i_ahb_AHB_Slave_PWM_hwrite(PWM_hwrite_top),
    // PWM out
    .out_pwm(out_pwm_top)
);
