// This file was automatically generated by coreAssembler (version J-2015.03-SP1).
// 
// FILENAME : /home/warehouse/l.kirchner/566_project/stub_tb/SPI_tb/src/SPI_tb1.v
// DATE : 11/21/15 17:55:21
// ABSTRACT : Verilog top-level subsystem RTL.
// 

module SPI_tb1 (// Ports for Interface ex_i_ssi_APB_Slave
                ex_i_ssi_APB_Slave_paddr,
                ex_i_ssi_APB_Slave_penable,
                ex_i_ssi_APB_Slave_psel,
                ex_i_ssi_APB_Slave_pwdata,
                ex_i_ssi_APB_Slave_pwrite,
                ex_i_ssi_APB_Slave_prdata,
                // Ports for Interface ex_i_ssi_PCLK
                ex_i_ssi_PCLK_pclk,
                // Ports for Interface ex_i_ssi_PRESETn
                ex_i_ssi_PRESETn_presetn,
                // Ports for Manually exported pins
                i_ssi_rxd,
                i_ssi_ss_in_n,
                i_ssi_ssi_clk,
                i_ssi_ssi_rst_n,
                i_ssi_sclk_out,
                i_ssi_ss_0_n,
                i_ssi_ssi_mst_intr_n,
                i_ssi_ssi_oe_n,
                i_ssi_ssi_rxf_intr_n,
                i_ssi_ssi_rxo_intr_n,
                i_ssi_ssi_rxu_intr_n,
                i_ssi_ssi_sleep,
                i_ssi_ssi_txe_intr_n,
                i_ssi_ssi_txo_intr_n,
                i_ssi_txd
                );

   // Ports for Interface ex_i_ssi_APB_Slave
   input  [7:0]   ex_i_ssi_APB_Slave_paddr;
   input          ex_i_ssi_APB_Slave_penable;
   input          ex_i_ssi_APB_Slave_psel;
   input  [31:0]  ex_i_ssi_APB_Slave_pwdata;
   input          ex_i_ssi_APB_Slave_pwrite;
   output [31:0]  ex_i_ssi_APB_Slave_prdata;
   // Ports for Interface ex_i_ssi_PCLK
   input          ex_i_ssi_PCLK_pclk;
   // Ports for Interface ex_i_ssi_PRESETn
   input          ex_i_ssi_PRESETn_presetn;
   // Ports for Manually exported pins
   input          i_ssi_rxd;
   input          i_ssi_ss_in_n;
   input          i_ssi_ssi_clk;
   input          i_ssi_ssi_rst_n;
   output         i_ssi_sclk_out;
   output         i_ssi_ss_0_n;
   output         i_ssi_ssi_mst_intr_n;
   output         i_ssi_ssi_oe_n;
   output         i_ssi_ssi_rxf_intr_n;
   output         i_ssi_ssi_rxo_intr_n;
   output         i_ssi_ssi_rxu_intr_n;
   output         i_ssi_ssi_sleep;
   output         i_ssi_ssi_txe_intr_n;
   output         i_ssi_ssi_txo_intr_n;
   output         i_ssi_txd;


   i_ssi_DW_apb_ssi i_ssi
      (.pclk           (ex_i_ssi_PCLK_pclk),
       .presetn        (ex_i_ssi_PRESETn_presetn),
       .psel           (ex_i_ssi_APB_Slave_psel),
       .penable        (ex_i_ssi_APB_Slave_penable),
       .pwrite         (ex_i_ssi_APB_Slave_pwrite),
       .paddr          (ex_i_ssi_APB_Slave_paddr),
       .pwdata         (ex_i_ssi_APB_Slave_pwdata),
       .rxd            (i_ssi_rxd),
       .ss_in_n        (i_ssi_ss_in_n),
       .ssi_clk        (i_ssi_ssi_clk),
       .ssi_rst_n      (i_ssi_ssi_rst_n),
       .prdata         (ex_i_ssi_APB_Slave_prdata),
       .ssi_sleep      (i_ssi_ssi_sleep),
       .txd            (i_ssi_txd),
       .sclk_out       (i_ssi_sclk_out),
       .ss_0_n         (i_ssi_ss_0_n),
       .ssi_oe_n       (i_ssi_ssi_oe_n),
       .ssi_txe_intr_n (i_ssi_ssi_txe_intr_n),
       .ssi_txo_intr_n (i_ssi_ssi_txo_intr_n),
       .ssi_rxf_intr_n (i_ssi_ssi_rxf_intr_n),
       .ssi_rxo_intr_n (i_ssi_ssi_rxo_intr_n),
       .ssi_rxu_intr_n (i_ssi_ssi_rxu_intr_n),
       .ssi_mst_intr_n (i_ssi_ssi_mst_intr_n));



endmodule
