// This file was automatically generated by coreAssembler (version J-2015.03-SP1).
// 
// FILENAME : /home/warehouse/l.kirchner/566_project/coreAssembler_ip/src/interconnect_ip.v
// DATE : 11/21/15 14:20:21
// ABSTRACT : Verilog top-level subsystem RTL.
// 

module interconnect_ip (// Ports for Interface HCLK
                        HCLK_hclk,
                        // Ports for Interface HRESETn
                        HRESETn_hresetn,
                        // Ports for Interface PCLK
                        PCLK_pclk,
                        // Ports for Interface PRESETn
                        PRESETn_presetn,
                        // Ports for Interface ex_i_ahb_AHB_Master
                        ex_i_ahb_AHB_Master_haddr,
                        ex_i_ahb_AHB_Master_hburst,
                        ex_i_ahb_AHB_Master_hbusreq,
                        ex_i_ahb_AHB_Master_hlock,
                        ex_i_ahb_AHB_Master_hprot,
                        ex_i_ahb_AHB_Master_hsize,
                        ex_i_ahb_AHB_Master_htrans,
                        ex_i_ahb_AHB_Master_hwdata,
                        ex_i_ahb_AHB_Master_hwrite,
                        ex_i_ahb_AHB_Master_hgrant,
                        ex_i_ahb_AHB_Master_hrdata,
                        ex_i_ahb_AHB_Master_hready,
                        ex_i_ahb_AHB_Master_hresp,
                        // Ports for Manually exported pins
                        i_apb_pclk_en,
                        i_i2c_ic_clk,
                        i_i2c_ic_clk_in_a,
                        i_i2c_ic_data_in_a,
                        i_i2c_ic_rst_n,
                        i_ssi_rxd,
                        i_ssi_ss_in_n,
                        i_ssi_ssi_clk,
                        i_ssi_ssi_rst_n,
                        i_ahb_hmaster_data,
                        i_i2c_debug_addr,
                        i_i2c_debug_addr_10bit,
                        i_i2c_debug_data,
                        i_i2c_debug_hs,
                        i_i2c_debug_master_act,
                        i_i2c_debug_mst_cstate,
                        i_i2c_debug_p_gen,
                        i_i2c_debug_rd,
                        i_i2c_debug_s_gen,
                        i_i2c_debug_slave_act,
                        i_i2c_debug_slv_cstate,
                        i_i2c_debug_wr,
                        i_i2c_ic_activity_intr,
                        i_i2c_ic_clk_oe,
                        i_i2c_ic_current_src_en,
                        i_i2c_ic_data_oe,
                        i_i2c_ic_en,
                        i_i2c_ic_gen_call_intr,
                        i_i2c_ic_rd_req_intr,
                        i_i2c_ic_rx_done_intr,
                        i_i2c_ic_rx_full_intr,
                        i_i2c_ic_rx_over_intr,
                        i_i2c_ic_rx_under_intr,
                        i_i2c_ic_start_det_intr,
                        i_i2c_ic_stop_det_intr,
                        i_i2c_ic_tx_abrt_intr,
                        i_i2c_ic_tx_empty_intr,
                        i_i2c_ic_tx_over_intr,
                        i_ssi_sclk_out,
                        i_ssi_ss_0_n,
                        i_ssi_ssi_mst_intr_n,
                        i_ssi_ssi_oe_n,
                        i_ssi_ssi_rxf_intr_n,
                        i_ssi_ssi_rxo_intr_n,
                        i_ssi_ssi_rxu_intr_n,
                        i_ssi_ssi_sleep,
                        i_ssi_ssi_txe_intr_n,
                        i_ssi_ssi_txo_intr_n,
                        i_ssi_txd
                        );

   // Ports for Interface HCLK
   input          HCLK_hclk;
   // Ports for Interface HRESETn
   input          HRESETn_hresetn;
   // Ports for Interface PCLK
   input          PCLK_pclk;
   // Ports for Interface PRESETn
   input          PRESETn_presetn;
   // Ports for Interface ex_i_ahb_AHB_Master
   input  [31:0]  ex_i_ahb_AHB_Master_haddr;
   input  [2:0]   ex_i_ahb_AHB_Master_hburst;
   input          ex_i_ahb_AHB_Master_hbusreq;
   input          ex_i_ahb_AHB_Master_hlock;
   input  [3:0]   ex_i_ahb_AHB_Master_hprot;
   input  [2:0]   ex_i_ahb_AHB_Master_hsize;
   input  [1:0]   ex_i_ahb_AHB_Master_htrans;
   input  [31:0]  ex_i_ahb_AHB_Master_hwdata;
   input          ex_i_ahb_AHB_Master_hwrite;
   output         ex_i_ahb_AHB_Master_hgrant;
   output [31:0]  ex_i_ahb_AHB_Master_hrdata;
   output         ex_i_ahb_AHB_Master_hready;
   output [1:0]   ex_i_ahb_AHB_Master_hresp;
   // Ports for Manually exported pins
   input          i_apb_pclk_en;
   input          i_i2c_ic_clk;
   input          i_i2c_ic_clk_in_a;
   input          i_i2c_ic_data_in_a;
   input          i_i2c_ic_rst_n;
   input          i_ssi_rxd;
   input          i_ssi_ss_in_n;
   input          i_ssi_ssi_clk;
   input          i_ssi_ssi_rst_n;
   output [3:0]   i_ahb_hmaster_data;
   output         i_i2c_debug_addr;
   output         i_i2c_debug_addr_10bit;
   output         i_i2c_debug_data;
   output         i_i2c_debug_hs;
   output         i_i2c_debug_master_act;
   output [4:0]   i_i2c_debug_mst_cstate;
   output         i_i2c_debug_p_gen;
   output         i_i2c_debug_rd;
   output         i_i2c_debug_s_gen;
   output         i_i2c_debug_slave_act;
   output [3:0]   i_i2c_debug_slv_cstate;
   output         i_i2c_debug_wr;
   output         i_i2c_ic_activity_intr;
   output         i_i2c_ic_clk_oe;
   output         i_i2c_ic_current_src_en;
   output         i_i2c_ic_data_oe;
   output         i_i2c_ic_en;
   output         i_i2c_ic_gen_call_intr;
   output         i_i2c_ic_rd_req_intr;
   output         i_i2c_ic_rx_done_intr;
   output         i_i2c_ic_rx_full_intr;
   output         i_i2c_ic_rx_over_intr;
   output         i_i2c_ic_rx_under_intr;
   output         i_i2c_ic_start_det_intr;
   output         i_i2c_ic_stop_det_intr;
   output         i_i2c_ic_tx_abrt_intr;
   output         i_i2c_ic_tx_empty_intr;
   output         i_i2c_ic_tx_over_intr;
   output         i_ssi_sclk_out;
   output         i_ssi_ss_0_n;
   output         i_ssi_ssi_mst_intr_n;
   output         i_ssi_ssi_oe_n;
   output         i_ssi_ssi_rxf_intr_n;
   output         i_ssi_ssi_rxo_intr_n;
   output         i_ssi_ssi_rxu_intr_n;
   output         i_ssi_ssi_sleep;
   output         i_ssi_ssi_txe_intr_n;
   output         i_ssi_ssi_txo_intr_n;
   output         i_ssi_txd;

   wire [31:0]  i_ahb_haddr;
   wire [2:0]   i_ahb_hburst;
   wire         i_ahb_hready;
   wire         i_ahb_hsel_s1;
   wire [2:0]   i_ahb_hsize;
   wire [1:0]   i_ahb_htrans;
   wire [31:0]  i_ahb_hwdata;
   wire         i_ahb_hwrite;
   wire [31:0]  i_apb_hrdata;
   wire         i_apb_hready_resp;
   wire [1:0]   i_apb_hresp;
   wire [31:0]  i_apb_paddr;
   wire         i_apb_penable;
   wire         i_apb_psel_s0;
   wire         i_apb_psel_s1;
   wire [31:0]  i_apb_pwdata;
   wire         i_apb_pwrite;
   wire [31:0]  i_i2c_prdata;
   wire [31:0]  i_ssi_prdata;

   i_ahb_DW_ahb i_ahb
      (.hclk           (HCLK_hclk),
       .hresetn        (HRESETn_hresetn),
       .haddr_m1       (ex_i_ahb_AHB_Master_haddr),
       .hburst_m1      (ex_i_ahb_AHB_Master_hburst),
       .hbusreq_m1     (ex_i_ahb_AHB_Master_hbusreq),
       .hlock_m1       (ex_i_ahb_AHB_Master_hlock),
       .hprot_m1       (ex_i_ahb_AHB_Master_hprot),
       .hsize_m1       (ex_i_ahb_AHB_Master_hsize),
       .htrans_m1      (ex_i_ahb_AHB_Master_htrans),
       .hwdata_m1      (ex_i_ahb_AHB_Master_hwdata),
       .hwrite_m1      (ex_i_ahb_AHB_Master_hwrite),
       .hgrant_m1      (ex_i_ahb_AHB_Master_hgrant),
       .hsel_s1        (i_ahb_hsel_s1),
       .hready_resp_s1 (i_apb_hready_resp),
       .hresp_s1       (i_apb_hresp),
       .hrdata_s1      (i_apb_hrdata),
       .haddr          (i_ahb_haddr),
       .hburst         (i_ahb_hburst),
       .hprot          (),
       .hsize          (i_ahb_hsize),
       .htrans         (i_ahb_htrans),
       .hwdata         (i_ahb_hwdata),
       .hwrite         (i_ahb_hwrite),
       .hready         (i_ahb_hready),
       .hresp          (ex_i_ahb_AHB_Master_hresp),
       .hrdata         (ex_i_ahb_AHB_Master_hrdata),
       .hmaster        (),
       .hmaster_data   (i_ahb_hmaster_data),
       .hmastlock      ());

   i_apb_DW_apb i_apb
      (.hclk        (HCLK_hclk),
       .hresetn     (HRESETn_hresetn),
       .haddr       (i_ahb_haddr),
       .hready      (i_ahb_hready),
       .hsel        (i_ahb_hsel_s1),
       .htrans      (i_ahb_htrans),
       .hwrite      (i_ahb_hwrite),
       .hsize       (i_ahb_hsize),
       .hburst      (i_ahb_hburst),
       .hresp       (i_apb_hresp),
       .hready_resp (i_apb_hready_resp),
       .hwdata      (i_ahb_hwdata),
       .hrdata      (i_apb_hrdata),
       .pclk_en     (i_apb_pclk_en),
       .paddr       (i_apb_paddr),
       .penable     (i_apb_penable),
       .pwrite      (i_apb_pwrite),
       .pwdata      (i_apb_pwdata),
       .psel_s1     (i_apb_psel_s1),
       .psel_s0     (i_apb_psel_s0),
       .prdata_s1   (i_ssi_prdata),
       .prdata_s0   (i_i2c_prdata));

   i_i2c_DW_apb_i2c i_i2c
      (.ic_start_det_intr (i_i2c_ic_start_det_intr),
       .ic_stop_det_intr  (i_i2c_ic_stop_det_intr),
       .ic_activity_intr  (i_i2c_ic_activity_intr),
       .ic_rx_done_intr   (i_i2c_ic_rx_done_intr),
       .ic_tx_abrt_intr   (i_i2c_ic_tx_abrt_intr),
       .ic_rd_req_intr    (i_i2c_ic_rd_req_intr),
       .ic_tx_empty_intr  (i_i2c_ic_tx_empty_intr),
       .ic_tx_over_intr   (i_i2c_ic_tx_over_intr),
       .ic_rx_full_intr   (i_i2c_ic_rx_full_intr),
       .ic_rx_over_intr   (i_i2c_ic_rx_over_intr),
       .ic_rx_under_intr  (i_i2c_ic_rx_under_intr),
       .ic_gen_call_intr  (i_i2c_ic_gen_call_intr),
       .ic_current_src_en (i_i2c_ic_current_src_en),
       .pclk              (PCLK_pclk),
       .presetn           (PRESETn_presetn),
       .psel              (i_apb_psel_s0),
       .penable           (i_apb_penable),
       .pwrite            (i_apb_pwrite),
       .paddr             (i_apb_paddr[7:0]),
       .pwdata            (i_apb_pwdata),
       .prdata            (i_i2c_prdata),
       .ic_clk            (i_i2c_ic_clk),
       .ic_clk_in_a       (i_i2c_ic_clk_in_a),
       .ic_data_in_a      (i_i2c_ic_data_in_a),
       .ic_rst_n          (i_i2c_ic_rst_n),
       .debug_s_gen       (i_i2c_debug_s_gen),
       .debug_p_gen       (i_i2c_debug_p_gen),
       .debug_data        (i_i2c_debug_data),
       .debug_addr        (i_i2c_debug_addr),
       .debug_rd          (i_i2c_debug_rd),
       .debug_wr          (i_i2c_debug_wr),
       .debug_hs          (i_i2c_debug_hs),
       .debug_master_act  (i_i2c_debug_master_act),
       .debug_slave_act   (i_i2c_debug_slave_act),
       .debug_addr_10bit  (i_i2c_debug_addr_10bit),
       .debug_mst_cstate  (i_i2c_debug_mst_cstate),
       .debug_slv_cstate  (i_i2c_debug_slv_cstate),
       .ic_clk_oe         (i_i2c_ic_clk_oe),
       .ic_data_oe        (i_i2c_ic_data_oe),
       .ic_en             (i_i2c_ic_en));

   i_ssi_DW_apb_ssi i_ssi
      (.pclk           (PCLK_pclk),
       .presetn        (PRESETn_presetn),
       .psel           (i_apb_psel_s1),
       .penable        (i_apb_penable),
       .pwrite         (i_apb_pwrite),
       .paddr          (i_apb_paddr[7:0]),
       .pwdata         (i_apb_pwdata),
       .rxd            (i_ssi_rxd),
       .ss_in_n        (i_ssi_ss_in_n),
       .ssi_clk        (i_ssi_ssi_clk),
       .ssi_rst_n      (i_ssi_ssi_rst_n),
       .prdata         (i_ssi_prdata),
       .ssi_sleep      (i_ssi_ssi_sleep),
       .txd            (i_ssi_txd),
       .sclk_out       (i_ssi_sclk_out),
       .ss_0_n         (i_ssi_ss_0_n),
       .ssi_oe_n       (i_ssi_ssi_oe_n),
       .ssi_txe_intr_n (i_ssi_ssi_txe_intr_n),
       .ssi_txo_intr_n (i_ssi_ssi_txo_intr_n),
       .ssi_rxf_intr_n (i_ssi_ssi_rxf_intr_n),
       .ssi_rxo_intr_n (i_ssi_ssi_rxo_intr_n),
       .ssi_rxu_intr_n (i_ssi_ssi_rxu_intr_n),
       .ssi_mst_intr_n (i_ssi_ssi_mst_intr_n));

   assign ex_i_ahb_AHB_Master_hready = i_ahb_hready;

   // Note: i_apb_paddr[31:8] is open

endmodule
