# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2014.4
# Copyright (C) 2014 Xilinx Inc. All rights reserved.
# 
# ==============================================================


/project/linuxlab/xilinx/xilinx/Vivado_HLS/Vivado_HLS/../../Vivado/Vivado_HLS/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z010clg400-1 ../xilinx_com_hls_gen_pwm_1_0.zip
